algoritmo "ex1"
var
   mes: inteiro
inicio
   escreva("Digite o numero do mes (1-12): ")
   leia(mes)
   escolha mes
      caso 1
         escreval("Janeiro")
      caso 2
         escreval("Fevereiro")
      caso 3
         escreval("Marco")
      caso 4
         escreval("Abril")
      caso 5
         escreval("Maio")
      caso 6
         escreval("Junho")
      caso 7
         escreval("Julho")
      caso 8
         escreval("Agosto")
      caso 9
         escreval("Setembro")
      caso 10
         escreval("Outubro")
      caso 11
         escreval("Novembro")
      caso 12
         escreval("Dezembro")
      outrocaso
         escreval("Erro: O numero digitado nao corresponde a um mes valido.")
   fimescolha
fimalgoritmo